fix: resolves api_unit_test token creation + datastore permissions issues
GoogleCloudPlatform/emblem pull request #665
Opened 2022-09-21 05:28 UTC by pattishin

**Issue:** 
Resolves token retrieval error in `unit-tests.cloudbuild.yaml`. The curl fetch for new generated id token was throwing 
```
{'error': {'code': 403, 'message': 'The caller does not have permission', 'status': 'PERMISSION_DENIED'}}
```
permissions error due to the `cloudbuild` service account not given the correct roles. (

**To recreate bug:**
 -  **Required:** You should have a working full setup of Emblem already
 - Create a new branch. Make any small change and create a pull request to trigger `api-unit-tests`. 
 - You should a series of errors related to firestore database and permissions errors.

**Fixes:**
 - Adding `roles/datastore.user` (firestore), `roles/iam.serviceAccountTokenCreator` roles to cloudbuild service account

2022-09-21 16:58 UTC, pattishin commented
hold please, will resolve the terraform fmt issue

2022-09-21 17:35 UTC, rogerthatdev commented on terraform/modules/ops/variables.tf
> +variable "pubsub_iam_roles_list" {
move these into a locals {} block instead of variables. 

We would use variables only for values that we would want an end user to change

2022-09-21 17:36 UTC, rogerthatdev commented on terraform/modules/ops/main.tf
> +  count = length(var.pubsub_iam_roles_list)
replace count with a for_each

2022-09-23 01:51 UTC, pattishin commented
Ready for 👀 again!

2022-09-23 17:10 UTC, rogerthatdev requested changes
just one nit!

2022-09-23 17:10 UTC, rogerthatdev commented on terraform/modules/ops/services.tf
> +  # Cloud build service account roles
This works, but to keep this file just for services, add a local block with this value at the top of `main.tf` instead.

2022-09-23 18:18 UTC, merged