mordenize cloud build yaml files with script
GoogleCloudPlatform/emblem pull request #913
Opened 2023-06-14 17:40 UTC by smeet07

addresses #790

2023-06-14 18:02 UTC, smeet07 commented
@grayside

2023-06-15 17:06 UTC, pattishin commented
/gcbrun

2023-06-15 22:14 UTC, pattishin commented
Hi @smeet07, appreciate the PR! Do you mind checking out the current failure in `api-unit-tests`?

<img width="621" alt="Screenshot 2023-06-15 at 3 10 53 PM" src="https://github.com/GoogleCloudPlatform/emblem/assets/1331216/69b09b1b-7b06-45e0-b26d-f82b4c2646c7">

2023-06-15 22:54 UTC, pattishin commented
Hi @smeet07, appreciate the change! It looks like the `api-unit-tests` did not pass. Do you mind looking into it?

2023-06-16 16:53 UTC, smeet07 commented
> Hi @smeet07, appreciate the change! It looks like the `api-unit-tests` did not pass. Do you mind looking into it?

It says you need permissions to view the details

2023-06-18 21:16 UTC, smeet07 commented
@pattishin

2023-06-20 22:46 UTC, pattishin commented
/gcbrun

2023-06-22 22:28 UTC, rogerthatdev commented
/gcbrun

2023-06-22 22:45 UTC, rogerthatdev commented
/gcbrun

2023-06-22 23:09 UTC, pattishin commented
/gcbrun

2023-06-22 23:32 UTC, rogerthatdev commented
@smeet07 
Thanks for the contribution!

In my testing I found that there is an issue having to do with variable substitution in your changes. For example, when initiating the `web-new-build` Cloud Build trigger that uses config `ops/web-build.cloudbuild.yaml` it returns the following error:
```
invalid argument "-docker.pkg.dev//website/website:" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 125
```

`-docker.pkg.dev//website/website:` in the build config reads `${_REGION}-docker.pkg.dev/${PROJECT_ID}/website/website:${_IMAGE_TAG} ` but the `script` field does not  support values from the [`substitution` field of the build config](https://github.com/GoogleCloudPlatform/emblem/blob/4be1a2f76f7b684f427d74db0209506e3d60f5af/ops/web-build.cloudbuild.yaml#L30C1-L32C25) 

Instead, each step that uses the `script` field with substitution values needs to also include an `env` field that will pass values to the script via environment variables. For example, for the `ops/web-build.cloudbuild.yaml`: 
```
steps:
  # Docker Build 
  # Copying the client-libs for Docker context
  - name: gcr.io/cloud-builders/docker
   env:
    - '_REGION=$_REGION'
    - 'PROJECT_ID=$PROJECT_ID'
    - '_IMAGE_TAG=$_IMAGE_TAG'
    script: |
      #!/usr/bin/env bash
      cp -R client-libs/ website/client-libs
      docker build -t \
      ${_REGION}-docker.pkg.dev/${PROJECT_ID}/website/website:${_IMAGE_TAG} \
      website/. 
```

You can can find more information about the `script` field and substitutions [right here](https://cloud.google.com/build/docs/configuring-builds/run-bash-scripts#using_substitutions_with_the_script_field).

2023-06-22 23:33 UTC, rogerthatdev commented on ops/web-build.cloudbuild.yaml
> +      docker build -t \
Cloud Build will not read values for these variables. Include an `env` field to remedy: 
```
  - name: gcr.io/cloud-builders/docker
   env:
    - '_REGION=$_REGION'
    - 'PROJECT_ID=$PROJECT_ID'
    - '_IMAGE_TAG=$_IMAGE_TAG'
```

2023-06-22 23:34 UTC, rogerthatdev requested changes
Thanks for the contribution!

In my testing I found that there is an issue having to do with variable substitution in your changes. For example, when initiating the `web-new-build` Cloud Build trigger that uses config `ops/web-build.cloudbuild.yaml` it returns the following error:
```
invalid argument "-docker.pkg.dev//website/website:" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 125
```

`-docker.pkg.dev//website/website:` in the build config reads `${_REGION}-docker.pkg.dev/${PROJECT_ID}/website/website:${_IMAGE_TAG} ` but the `script` field does not  support values from the [`substitution` field of the build config](https://github.com/GoogleCloudPlatform/emblem/blob/4be1a2f76f7b684f427d74db0209506e3d60f5af/ops/web-build.cloudbuild.yaml#L30C1-L32C25) 

Instead, each step that uses the `script` field with substitution values needs to also include an `env` field that will pass values to the script via environment variables. For example, for the `ops/web-build.cloudbuild.yaml`: 
```
steps:
  # Docker Build 
  # Copying the client-libs for Docker context
  - name: gcr.io/cloud-builders/docker
   env:
    - '_REGION=$_REGION'
    - 'PROJECT_ID=$PROJECT_ID'
    - '_IMAGE_TAG=$_IMAGE_TAG'
    script: |
      #!/usr/bin/env bash
      cp -R client-libs/ website/client-libs
      docker build -t \
      ${_REGION}-docker.pkg.dev/${PROJECT_ID}/website/website:${_IMAGE_TAG} \
      website/. 
```

You can can find more information about the `script` field and substitutions [right here](https://cloud.google.com/build/docs/configuring-builds/run-bash-scripts#using_substitutions_with_the_script_field).

2023-06-22 23:38 UTC, smeet07 commented
Oh I did not know script tag does not support substitution variables. Sorry for not doing the research beforehand, I’ll make the appropriate changes

2023-06-25 05:55 UTC, smeet07 commented
@rogerthatdev need /gcbrun from you to test the api-unit-tests

2023-06-26 18:22 UTC, pattishin commented
@smeet07 `failed unmarshalling build config ops/unit-tests.cloudbuild.yaml: json: cannot unmarshal string into Go value of type []json.RawMessage` 

<img width="993" alt="Screenshot 2023-06-26 at 10 30 10 AM" src="https://github.com/GoogleCloudPlatform/emblem/assets/1331216/ec59f80c-073b-4701-8454-3d0e9ebc8d14">

To validate that the cloud build trigger above is working on your end, do setup this project on a personal GCP project (https://github.com/GoogleCloudPlatform/emblem/tree/main/docs). It will take 15-20 minutes to fully set this up via terraform and execute the trigger by simply updating anything within `content-api/` dir.

2023-06-26 18:38 UTC, pattishin commented
/gcbrun

2023-06-29 10:44 UTC, smeet07 commented
> @smeet07 <img alt="Screenshot 2023-06-26 at 10 30 10 AM" width="993" src="https://user-images.githubusercontent.com/1331216/248897372-ec59f80c-073b-4701-8454-3d0e9ebc8d14.png">
> 
> To validate that the `api-unit-tests` cloud build trigger is working on your end, do setup this project on a personal GCP project (https://github.com/GoogleCloudPlatform/emblem/tree/main/docs). It will take 15-20 minutes to fully set this up via terraform and execute the trigger by simply updating anything within `content-api/` dir.

I do not have a billing enabled gcp account at the moment, I'll see if I have credits left on my uni account. Meanwhile could you trigger the api-unit-tests build?

2023-06-30 05:21 UTC, smeet07 commented
There is no console output of the error, the problem might be due to #848

2023-06-30 05:27 UTC, smeet07 commented
> /gcbrun

@pattishin could you give me console output of the error

2023-07-05 19:04 UTC, pattishin commented
/gcbrun

2023-07-06 22:35 UTC, pattishin commented
/gcbrun

2023-07-07 02:11 UTC, pattishin requested changes
Hi @smeet07, running your fork locally is producing the following error. Adding some suggestions here to resolve and once those changes are in this should be ready to merge.

![Screenshot 2023-07-06 at 4 07 01 PM](https://github.com/GoogleCloudPlatform/emblem/assets/1331216/4b06b64c-8c0c-42ad-87e4-505b07d07685)

2023-07-07 20:47 UTC, smeet07 commented on ops/web-build.cloudbuild.yaml
>  substitutions:
So in the images section should I hardcode the values. Replace ${_REGION} with the hardcoded value 'us-central1', and ${_IMAGE_TAG} with '${SHORT_SHA}' ?

2023-07-10 17:10 UTC, pattishin commented
/gcbrun

2023-07-10 19:54 UTC, pattishin commented
/gcbrun

2023-07-11 18:15 UTC, smeet07 commented
> @smeet07 Thanks for the changes! Do you mind removing that last `substitution` block? I'll retest for you and get these changes in.

@pattishin I've made the changes

2023-07-12 17:47 UTC, pattishin commented
/gcbrun

2023-07-13 11:31 UTC, smeet07 commented
@pattishin I can see that the build is still failing , what is the error?

2023-07-17 17:47 UTC, pattishin approved these changes
@smeet07 It's a known issue that is not related to your PR (api unit test trigger). I just verified your PR manually. Thanks for your contribution!

2023-07-17 17:49 UTC, merged